dist: focal

os:
- linux

language: cpp

before_script:
- sudo apt-get update
- sudo apt-get -y install libxrandr-dev
- sudo apt-get -y install libxinerama-dev
- mkdir build
- cd build
- cmake ..

script:
- cmake --build build/

after_script:
	
