language: cpp

install:
  - python3 -m pip install --upgrade pip setuptools
  - python3 -m pip install conan cmake
  - conan --version

jobs:
  include:
    # Linux - Clang
    - os: linux
      dist: bionic
      compiler: clang
      env: 
        - MATRIX_EVAL="CC=clang && CXX=clang++"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - doxygen
            - python3-pip
            - clang-10

    # Linux - GCC
    - os: linux
      dist: bionic
      compiler: gcc
      env: 
        - GCC_VER="9"
        - MATRIX_EVAL="CC=gcc-${GCC_VER} && CXX=g++-${GCC_VER}"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - doxygen
            - python3-pip
            - gcc-9
            - g++-9

    # Linux - Ninja
    - os: linux
      dist: bionic
      compiler: ninja
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - doxygen
            - python3-pip
            - ninja-build

before_script:
  - eval "${MATRIX_EVAL}"

script:
  - mkdir build && cd build
  - conan install .. -s build_type=Debug
  - cmake .. -D CMAKE_BUILD_TYPE=Debug
  - cmake --build .

notification:
  email: false
