dist: focal

os: linux

language: cpp

addons:
  apt:
    update: true
    packages:
      - cmake
      - libxrandr-dev
      - libxinerama-dev
      - libxcursor-dev
      - libxi-dev
      - libxext-dev

script:
  - cmake -S . -B build/ -G "Unix Makefiles" "-DCMAKE_BUILD_TYPE=Debug"
  - cmake --build build/
