dist: focal

os:
- linux

language: cpp

before_script:
- sudo apt-get update
- sudo apt-get -y install libxrandr-dev
- sudo apt-get -y install libxinerama-dev
- sudo apt-get -y install libxcursor-dev
- sudo apt-get -y install libxi-dev
- sudo apt-get -y install libxext-dev
- cmake -S . -B build -G "Unix Makefiles" "-DCMAKE_BUILD_TYPE=Debug"

script:
- cmake --build build

after_script:
	
