dist: focal

os:
- linux

language: cpp

addons:
	apt:
		update: True

before_script:
- sudo apt -y install libxrandr-dev
- mkdir build
- cd build
- cmake ..

script:
- cmake --build build/

after_script:
	
