dist: focal

os:
- linux

language: cpp

before_script:
- sudo apt-get -y install libxrandr-dev
- mkdir build
- cd build
- cmake ..
addons:
  apt:
    update: true

script:
- cmake --build build/

after_script:
	
