name: "Hello World"
description: "Greet someone"

defaults:
  run:
    shell: bash

runs:
  using: "composite"
  steps:
    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: latest
        platform: x64

    - name: Set up GCC
      if: runner.os == 'linux'
      uses: egor-tensin/setup-gcc@v1
      with:
        version: latest
        platform: x64

    - name: Install system dependencies
      if: runner.os == 'linux'
      run: |
        sudo apt update -y
        sudo apt install -y \
            cmake \
            gcc \
            clang \
            ninja-build \
            python3-dev \
            python3-pip \
            pkg-config \
            libgl-dev \
            libx11-xcb-dev \
            libx11-xcb-dev \
            libfontenc-dev \
            libice-dev \
            libsm-dev \
            libxaw7-dev \
            libxcomposite-dev \
            libxcursor-dev \
            libxdamage-dev \
            libxi-dev \
            libxinerama-dev \
            libxkbfile-dev \
            libxmuu-dev \
            libxrandr-dev \
            libxres-dev \
            libxss-dev \
            libxtst-dev \
            libxv-dev \
            libxvmc-dev \
            libxxf86vm-dev \
            libxcb-render0-dev \
            libxcb-render-util0-dev \
            libxcb-xkb-dev \
            libxcb-icccm4-dev \
            libxcb-image0-dev \
            libxcb-keysyms1-dev \
            libxcb-randr0-dev \
            libxcb-shape0-dev \
            libxcb-sync-dev \
            libxcb-xfixes0-dev \
            libxcb-xinerama0-dev \
            libxcb-dri3-dev \
            libxcb-util-dev \
            libxcb-util0-dev \
            uuid-dev
        pip3 install conan
        export PATH=$PATH:~/.local/bin
