name: Release

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Update apt-get
      run: |
           sudo apt-get update -y

    - name: Install Conan
      run: |
           pip3 install wheel setuptools
           pip3 install conan
           export PATH=$PATH:/home/runner/.local/bin

    - name: Configure Conan
      run: >
        conan install . 
        --install-folder ${{github.workspace}}/build 
        --settings build_type=${{env.BUILD_TYPE}}
        --build missing

    - name: Configure CMake
      run: > 
        cmake -B ${{github.workspace}}/build -D 
        CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: >
        cmake --build ${{github.workspace}}/build

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
