name: test-linux

on: 
  push:
  pull_request:
    branches: [main]

defaults:
  run:
    shell: bash

env:
  source_dir: "${{github.workspace}}"
  build_dir: "${{github.workspace}}/build"

jobs:
  build:
    name: "build-${{matrix.os}}-${{matrix.compiler.c}}-${{matrix.build_type}}"
    runs-on: "${{matrix.os}}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            compiler: { c: gcc, cpp: g++ }
            generator: Ninja
            build_type: Release
            platform: x64

          - os: ubuntu-20.04
            compiler: { c: clang, cpp: clang++ }
            generator: Ninja
            build_type: Release
            platform: x64

          - os: ubuntu-18.04
            compiler: { c: gcc, cpp: g++ }
            generator: Ninja
            build_type: Release
            platform: x64

          - os: ubuntu-18.04
            compiler: { c: clang, cpp: clang++ }
            generator: Ninja
            build_type: Release
            platform: x64

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Environment setup
      uses: ./.github/actions/linux-setup

    - name: Generate project build
      run: |
        export CMAKE_GENERATOR="${{matrix.generator}}"
        export CMAKE_C_COMPILER="${{matrix.compiler.c}}"
        export CMAKE_CXX_COMPILER="${{matrix.compiler.cpp}}"
        cmake \
          -S ${{env.source_dir}} \
          -B ${{env.build_dir}} \
          -D CMAKE_BUILD_TYPE=${{env.build_type}} \
          -D PINE_EDITOR_ENABLE=ON \
          -D PINE_EXAMPLE_ENABLE=ON \
          -D PINE_TEST_ENABLE=ON

    - name: Build project
      run: cmake --build ${{env.build_dir}}

  test:
    name: "test-${{matrix.os}}-${{matrix.compiler.c}}-${{matrix.build_type}}"
    needs: build
    runs-on: "${{matrix.os}}"
    steps:
    - name: Run project tests
      run: |
        cd ${{env.build_dir}}
        ctest
