name: test-linux

on: 
  push:
  pull_request:
    branches: [main]

defaults:
  run:
    shell: bash 
env:
  source_dir: "${{github.workspace}}"

jobs:
  build_and_test:
    name: "test-${{matrix.os}}-${{matrix.build_type}}-${{matrix.compiler}}"
    runs-on: "${{matrix.os}}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            compiler: gcc
            generator: Ninja
            build_type: Release
            platform: x64

          - os: ubuntu-20.04
            compiler: clang
            generator: Ninja
            build_type: Release
            platform: x64

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Environment setup
      uses: ./.github/actions/linux-setup

    - name: Create Conan profile
      run: |
        conan profile detect
        conan profile detect --name worker_profile

    - name: Build
      run: |
        conan build ${{env.source_dir}} \
            -s build_type=${{matrix.build_type}} \
            -s compiler=${{matrix.compiler}} \
            -s compiler.cppstd=17 \
            -pr:b=worker_profile \
            --build missing

    - name: Run project tests
      run: |
        cd ${{env.build_dir}}
        ctest
