# Reusable workflow base for project setup, building, and testing.
name: Windows Base

on:
  workflow_call:
    inputs:
      build_type:
        description:
        default: "Release"
        required: true
        type: string

    secrets:
      token:
        required: false

jobs:
  setup:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v1

      - name: Install system requirements
        run: |
          choco install --yes ninja

      - name: Install Conan
        run: |
          pip3 install wheel setuptools
          pip3 install conan

      - name: Configure Conan
        run: >
          conan install . 
          --install-folder ${{ github.workspace }}/build 
          --settings build_type=${{ inputs.build_type }}
          --build missing

      - name: Configure CMake
        run: > 
          cmake -B ${{ github.workspace }}/build -D 
          CMAKE_BUILD_TYPE=${{ inputs.build_type }}

  build:
    needs: setup
    runs-on: windows-latest
    steps:
      - name: Build
        run: cmake --build ${{ github.workspace }}/build

  test:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: ctest -C ${{ inputs.build_type }}
